

import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import '../css/index.css'
import { Toaster } from '@/components/ui/toast';

import { cn } from '@/utils/theme';
import { MainHeader } from '@/components/header/main-header';
import { Sidebar } from '@/components/menu/sidebar-menu/sidebar';
import { getCurrentUser } from "@/auth/nextjs/currentUser"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  const fullUser = await getCurrentUser({ withFullUser: true })

  return (

    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <aside
          className={cn(
            'fixed bottom-0 start-0 z-50 h-full w-[270px] border-e-2 border-gray-100 dark:border-border bg-card dark:bg-sidebar-background 2xl:w-72 hidden xl:block',
          )}
        >
          <Sidebar />
        </aside>
        <main className="flex w-full flex-col xl:ms-[270px] xl:w-[calc(100%-270px)] 2xl:ms-72 2xl:w-[calc(100%-288px)]">
          <div className="sticky top-0 z-40 w-full">
            <MainHeader user={fullUser} />
          </div>

          <div className="w-full flex-1 overflow-y-auto">{children}</div>
        </main>


        <Toaster
          position="top-center"
          richColors
          duration={1500}
          visibleToasts={1}
        />
      </body>
    </html>
  )
}